name: Build and Release RA3 Converter

on:
  push:
    tags:
      - 'v*'

jobs:
  # --- TRABAJO PARA LINUX ---
  build-linux:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-tk python3-pil.imagetk
          python -m pip install --upgrade pip
          pip install pyinstaller ttkbootstrap pandas openpyxl xlrd Pillow

      - name: Build with PyInstaller
        run: |
          SHA_SHORT=$(git rev-parse --short HEAD)
          pyinstaller --noconfirm --onefile --windowed \
            --name "Convertidor_RA3_Linux_${{ github.ref_name }}_${SHA_SHORT}" \
            --add-data "io_sead.py:." \
            --collect-all ttkbootstrap \
            --hidden-import pandas \
            --hidden-import PIL._tkinter_finder \
            --collect-submodules PIL \
            "convertidor_RA3.py"

      - name: Upload Linux Asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/Convertidor_RA3_Linux_*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # --- TRABAJO PARA WINDOWS ---
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller ttkbootstrap pandas openpyxl xlrd Pillow

      - name: Build with PyInstaller
        shell: pwsh
        run: |
          $SHA_SHORT = (git rev-parse --short HEAD).Substring(0, 7)
          pyinstaller --noconfirm --onefile --windowed `
            --icon="ra3.ico" `
            --name "Convertidor_RA3_Win_${{ github.ref_name }}_$SHA_SHORT" `
            --add-data "io_sead.py;." `
            --collect-all ttkbootstrap `
            --hidden-import pandas `
            --collect-submodules PIL `
            "convertidor_RA3.py"

      - name: Upload Windows Asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/Convertidor_RA3_Win_*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
